### ISSUE TITLE
requirment of fastq input

### ISSUE THREAD

**Issue by Sudolin** [sjdlabgroup/SAHMI#1]
Dear author,

Thank you for such a great tool.

10X fastq fiels has at least 2 fastq files consisting of  barcodes, and reads. Usually, the fastq file storing barcode sequences have 26 bp. I am wondering whether I could use these fastqs directly as the input of SAHMI pipeline. 

In addition, do single-cell rna-seq data generated by Drop-seq or BD Rhapsody could be directly used for SAHMI?

Thank you in advance.

Leo Lin

**Comment by sjdlabgroup** [comment]
Hi Leo, yes you can still use the paired fastq files where the read 1 only contains the barcode and UMI. 
We have used SAHMI on Drop-seq data but no BD Rhapsody. Feel free to try!
