### ISSUE TITLE
commond line format in using run_kraken.r

### ISSUE THREAD

**Issue by baike687** [sjdlabgroup/SAHMI#10]
Hi, excuse me, I am a beginner in commond line, and I was wondering where went wrong in the format:
`Rscript run_kraken.r --sample JXF_CA 
--fq1 /home/lbk/data/wangyue0921031/X101SC22033524-Z01-J065/00.CleanData/Jiangxiaofu-CA/Jiangxiaofu-CA_1.clean.fq.gz 
--fq2 /home/lbk/data/wangyue0921031/X101SC22033524-Z01-J065/00.CleanData/Jiangxiaofu-CA/Jiangxiaofu-CA_2.clean.fq.gz 
--kreport2mpa_path /home/lbk/apps/SAHMI-main/functions/kreport2mpa.py --ncbi_blast_path /home/lbk/apps/ncbi-blast-2.14.0/bin/dustmasker 
--out_path /home/lbk/Research_projects/test/SAHMI/ 
--Kraken2Uniq_path /home/lbk/github_repository/kraken2/kraken2-master/scripts/kraken2 
--kraken_database_path /home/lbk/github_repository/database_annotation/kraken2_std/ `

this returns `Error in paste0(str, "export PATH=$PATH:", opt$ncbi_blast_path, " \n\n",  : 
  cannot coerce type 'closure' to vector of type 'character'
Execution halted`

Many Thanks!

**Comment by Wang-Taiwei** [comment]
Add `str=""` before the first paste0 function in run_kraken.r file.

**Comment by baike687** [comment]
> Add `str=""` before the first paste0 function in run_kraken.r file.

Thanks, it helps!
