### ISSUE TITLE
Does kraken step remove host reads?

### ISSUE THREAD

**Issue by zyh4482** [sjdlabgroup/SAHMI#2]
Thanks for your wonderful tool! 

Said it is essential to remove host reads for SAHMI prior denoising, does `run_kraken.r` automatically remove host reads? 

I found some literatures mentioned using a human reference genome to remove reads via `bwa` or other aligners. If I understand correctly, does it mean I need to keep unmapped reads for kraken step? 

Would you mind give me some help? Thank you so much.

**Comment by AldrichCPU-bio** [comment]
> Thanks for your wonderful tool!
> 
> Said it is essential to remove host reads for SAHMI prior denoising, does `run_kraken.r` automatically remove host reads?
> 
> I found some literatures mentioned using a human reference genome to remove reads via `bwa` or other aligners. If I understand correctly, does it mean I need to keep unmapped reads for kraken step?
> 
> Would you mind give me some help? Thank you so much.


see `extract_microbiome_output.r` and `extract_microbiome_reads.r`

**Comment by sjdlabgroup** [comment]
Yes, you should configure Kraken to map to both human and microbial genomes. The "extract" scripts then take out only the microbial reads for further analysis. If you have already removed human reads by taking the unmapped reads after aligning to the human genome, that will still work - you can still use those unmapped reads as input to Kraken and SAHMI.
