### ISSUE TITLE
Question: shall I regard the host's cDNA sequence as reference genome?

### ISSUE THREAD

**Issue by AldrichCPU-bio** [sjdlabgroup/SAHMI#3]
Hi, I've read your article about SAHMI, good work! But I have a question about the reference genome. Why don't you adopt host's cDNA sequence as the reference? I think it might be more appropriate for RNA data.

**Comment by sjdlabgroup** [comment]
Thanks for the comment! That could be an option, but as currently configured SAHMI is appropriately removing host reads - hopefully our peer-reviewed manuscript will be available soon with an analysis to show that.
