### ISSUE TITLE
Thanks for the wonderful algorithm

### ISSUE THREAD

**Issue by Yunuuuu** [sjdlabgroup/SAHMI#5]
I have created a package based on this repo, I wish it would be helpful. I use re-write a lot code with data.table package, which I think could be accelarate the code. Especially the new `taxa_counts` function (can finish in 10 minutes) and `run_sckmer` function . I have also tested the results with the SAHMI in this repo, which validated to be the same.

**Comment by Yunuuuu** [comment]
The package is deposited in https://github.com/Yunuuuu/rsahmi

**Comment by sjdlabgroup** [comment]
Thank you for your contribution!
